### ISSUE TITLE
What does it mean if other genes can't generate plot?

### ISSUE THREAD

**Issue by nickbien** [NElnour/capsule#6]
As from testing, only DVL2 was able to generate plot of cell.

```
> whereIs("ZSCAN1", enhanced, "Approved")
 Error in `[.data.frame`(HPASet[hgnc_symbol, ], reliability) : 
undefined columns selected 
> whereIs("XRCC4", enhanced, "Enhanced")
Error in if (grep(";", as.character(HPASet[hgnc_symbol, ][reliability])) >  : 
  argument is of length zero
> whereIs("HCCS", enhanced, "Enhanced")
Error in if (grep(";", as.character(HPASet[hgnc_symbol, ][reliability])) >  : 
  argument is of length zero
> 
```

**Comment by NElnour** [comment]
Did you apply recent patch @54a27379d2b6ebd8eb18204dec0e09c657d8315d? It's merged to master

**Comment by nickbien** [comment]
Yes I did. Sorry I'm still trying to figure this out.

```
commit 54a27379d2b6ebd8eb18204dec0e09c657d8315d (HEAD -> master, origin/master, origin/HEAD)
Merge: 9a29b4e 82317d4
Author: Nada Elnour <nelnour90@gmail.com>
Date:   Thu May 5 03:40:25 2022 -0400

    Merge pull request #5 from NElnour/issue-2

    Patch singular location bug

commit 82317d4d8c5d6b8628bd9d7ed277e7bf6a9aa5ea (origin/issue-2)
Author: Nada Elnour <nelnour90@gmail.com>
Date:   Thu May 5 03:39:47 2022 -0400

    Patch singular location bug
```

```
> whereIs("DVL2", enhanced, "Enhanced")
Linking to librsvg 2.48.4
> whereIs("ZSCAN1", enhanced, "Approved") <<<< Approved is the actual reliability
 Error in `[.data.frame`(HPASet[hgnc_symbol, ], reliability) : 
undefined columns selected 
> whereIs("ZSCAN1", enhanced, "Enhanced")
> whereIs("HCCS", enhanced, "Enhanced")
 Error in UseMethod("depth") : 
no applicable method for 'depth' applied to an object of class "NULL" 
> whereIs("CDC27", enhanced, "Enhanced")
> whereIs("RECQL", enhanced, "Enhanced")
> whereIs("LAS1L", enhanced, "Approved") <<<<< THIS is the actual reliability but does not work and no error when using Enhanced (which is not the actual value in column).
 Error in `[.data.frame`(HPASet[hgnc_symbol, ], reliability) : 
undefined columns selected
```

**Comment by NElnour** [comment]
No worries. How did you generate enhanced?

----
Seeing that "Enhanced" generally works, I'm assuming `parseHPAData()` was called with default arg reliability="Enhanced". Generally, you won't be able to call "Approved" reliability on the generated set because it will be filtered for records with enhanced reliability only, If you want to visualize approved reliability, you'd have to parseHPAData with overriding reliability flag. I'll work on merging those two.

---
For 
`> whereIs("HCCS", enhanced, "Enhanced")`

I wasn't able to replicate the error but it looks like it's [related to plotting](https://github.com/tidyverse/ggplot2/issues/2514). Could you make sure that your plot window is sized big enough for the plots for now? I'll also add a ticket to enable export of plot by name and timestamp.

**Comment by nickbien** [comment]
Thank you @NElnour . I think your latest commit fixed it. I don't see any error now.
Thank you for your efforts!
